### PR TITLE
Update build.gradle to remove reference to windows file

### PR DESCRIPTION
**Pull request by sdstolworthy**

### CODE REVIEW

**Comment by sdstolworthy** [comment]
resolves #13

**Review by Rexios80 — APPROVED** [review]

**Comment by Rexios80** [comment]
Wait why am I allowed to do that 🤔

**Review by johnson-yeap — APPROVED** [review]

**Comment by slightfoot** [comment]
Thanks guys, like an idiot I left that line in.

**Comment by Rexios80** [comment]
@slightfoot If you open the example/android/build.gradle file in Android Studio the project resolves everything correctly and is much easier to deal with. I'm guessing that's why you had that line in there because that's how I used to do it too 🙃

**Pull request merged**
