### PR TITLE
Migrate to AndroidX and updates to build.gradle

### PR DESCRIPTION
**Pull request by outlandnish**
Updates the Kotlin Gradle Plugin, the Gradle Build Plugin, and the compileSdkVersion

### CODE REVIEW

**Comment by chunhunghan** [comment]
@nsamala , Could you please update example folder to AndroidX
Thank you very much.

**Comment by sbis04** [comment]
Please **merge** this pull request, this will fix all the **Gradle** related issues 🙏

**Comment by outlandnish** [comment]
I went ahead and updated the example too since it appears that was a blocker for merging this PR. I haven't tested the code because I don't have a Flutter dev environment setup atm, but it should work as the changes mirror the changes I made in the Flutter library.

**Comment by slightfoot** [comment]
Thanks for your contribution but this issue is now resolved in version `0.1.0` released yesterday. Closing issue.

**Pull request closed without merging**
