### PR TITLE
Fix android building

### PR DESCRIPTION
**Pull request by Rexios80**
Fixes:
```console
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/rexios/.pub-cache/hosted/pub.dartlang.org/wear-1.1.0/android/build.gradle'

* What went wrong:
Could not compile build file '/Users/rexios/.pub-cache/hosted/pub.dartlang.org/wear-1.1.0/android/build.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 63

  java.lang.IllegalArgumentException: Unsupported class file major version 63

  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
  	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
  	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)

...
```

Also updated the example app

### CODE REVIEW

**Review by Mstrodl — APPROVED** [review]
Works great for me, hope this can get merged soon

**Comment by Rexios80** [comment]
Related:
- https://github.com/flutter/flutter/issues/122376
- https://github.com/flutter/flutter/issues/122213

**Comment by reidbaker** [comment]
I cannot add reviewers but this looks like a good update to 
* The version of kotlin
* Targeting compileSdkVersion 33 which will be required for all new apps soon 
* Migration to applicationId in build.gradle and away from packageId in AndroidManifest 
* Updates to AGP and Gradle to the minimum supported versions by the next version of AndroidStudio Flamingo due to be released soon.

**Comment by Rexios80** [comment]
I released the [wear_plus](https://pub.dev/packages/wear_plus) plugin which contains the necessary fixes

**Pull request closed without merging**
